version: '3.8'
services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

#  for local development, you can use volumes to sync code changes
#     volumes:
#       - ./server:/usr/src/app
#     depends_on:
#       - db
#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: admin123
#       POSTGRES_DB: mydb
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data